CREATE TABLE reflections(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dateCreated TIMESTAMPTZ DEFAULT now() not NULL,
    title TEXT NOT NULL,
    image_url TEXT,
    description TEXT NOT NULL,
    feeling TEXT NOT NULL,
    content TEXT NOT NULL,
)